spring:
  datasource:
    driver-class-name: ${tsam-sync.datasource.driver}
    url: jdbc:mysql://${tsam-sync.datasource.host}:${tsam-sync.datasource.port}/${tsam-sync.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=${tsam-sync.datasource.timezone}